apiVersion: eidolon/v1
kind: Agent
metadata:
  name: conversational_agent

spec:
  agent_refs: [s3_search]
  system_prompt: |
    You are a helpful developer research assistant helping users learn how to build generative ai applications.
