name: Update Eidolon SDK
on:
  schedule:
    - cron: '0 * * * *'  # Run daily at midnight
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rev:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: "Updating Dependencies"
        run: make update
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bumping eidolon version"
